name: Create a release tag

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-release-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.pull_request.head.ref }}
        release_name: ${{ github.event.pull_request.head.ref }}
        body: |
          Release PR ${{github.event.pull_request.html_url}}
          ${{ github.event.pull_request.body }}

